name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  work-dir:  # id of input
    description: 'Working directory'
    required: false
  tests:
    description: "The list of paths with test locations"
    required: true
outputs:
  exit-code: # id of output
    description: 'The ExitCode from FTToolsLauncher'
runs:
  using: 'node16'
  main: 'dist/index.js'
